Api/Controller/LoginCheckInterface.php
Api/Observer/LoginRequiredObserverInterface.php
Controller/LoginCheck.php
Observer/LoginRequiredOnCustomerSessionInitObserver.php
Observer/LoginRequiredOnVisitorInitObserver.php
Repository/WhitelistRepository.php
Setup/UpgradeData.php
Setup/UpgradeSchema.php
Test/Unit/Controller/LoginCheckUnitTest.php
Ui/Component/Listing/Column/DeleteAction.php
Ui/Component/Listing/Column/StoreName.php
etc/di.xml

Improved unit tests
Fixed some minor coding style issues
Fixed missing preference in DI

Fixed issue with storefront prefix

---

Test/Unit/Repository/WhitelistRepositoryUnitTest.php
composer.json
composer.lock

Added support for Magento 2.1

---

Changelog.md
Controller/LoginCheck.php
Model/Session.php
Plugin/AfterLoginPlugin.php
Test/Unit/Controller/LoginCheckUnitTest.php
etc/di.xml

Feature/release r2.0.0 t35 redirect login

---

Changelog.md
Setup/UpgradeData.php
etc/di.xml

#43 Added additional default rules for sitemap.xml and robots.txt

---

Changelog.md
Controller/LoginCheck.php
Test/Unit/Controller/LoginCheckUnitTest.php

Feature/release r2.0.0 t26 cache control

---

Setup/UpgradeData.php

Resolve redirect loop from login to customer dashboard

---

etc/adminhtml/system.xml

#79 Fixed invalid position of tag resource in system.xml

---

etc/module.xml

Minor issue, should only effect marketplace, unless there are some migration (data, schema) steps to process.

Set module setup version to current release version

---

Test/Unit/Model/ResourceModel/WhitelistEntry/CollectionFactoryUnitTest.php
Test/Unit/Model/ResourceModel/WhitelistEntryUnitTest.php
build.xml
composer.json
composer.lock

Add Magento EQP tool in Travis build

---

Helper/Strategy/RegExAllNegationMatcher.php
README.md
Test/Unit/Helper/Strategy/RegExAllNegationMatcherUnitTest.php
etc/di.xml

This should solve the issue #126 
A new strategy has been added, negating the RegEx (All) strategy.

Issue #126 - added additional stategy for negated regex

---

bin/build
bin/setup
docker-compose.yml

Allow the local module files to be symlinked in the vendor folder within the docker container so that composer treats the local package as a composer package and installs all dependencies as needed.

Improve docker setup

---

Test/Unit/Controller/Adminhtml/Manage/DeleteUnitTest.php
Test/Unit/Controller/Adminhtml/Manage/EditUnitTest.php
Test/Unit/Controller/Adminhtml/Manage/IndexUnitTest.php
Test/Unit/Controller/Adminhtml/Manage/Redirect.php
phpunit.xml

Add more unit tests

---

.travis.yml
build.xml
captainhook.json
composer.json
composer.lock

Checks each composer dependency for security issues on every push and during each Travis build run.

Add bitexpert/phing-securitychecker dependency

---

Api/Controller/LoginCheckInterface.php
Controller/LoginCheck.php
Test/Unit/Controller/LoginCheckUnitTest.php
etc/adminhtml/system.xml
etc/module.xml

Add option to configure to force https redirect

---

Setup/UpgradeData.php
etc/module.xml

Add varnish ESI url to whitelist

---

.travis.yml
composer.json
composer.lock

Drop compatibility to reduce maintenance costs. Sorry.

Drop Magento 2.1 & 2.2 compatibility

---

.travis.yml
composer.json
composer.lock

Add PHP7.3 and Magento 2.3.3 version requirements

---

build.xml
composer.json
composer.lock

Requirement for updating the module in Marketplace.

Migrate to Magento Coding Standard

---

Controller/LoginCheck.php

Skip dynamic asset request

---

.github/workflows/ci.yml

Replace Travis build with GitHub Actions

Configure GitHub Actions

---

Controller/LoginCheck.php
Test/Unit/Controller/LoginCheckUnitTest.php

Allow a Magento Admin to log in as a customer when the module is active. See here for the discussion https://github.com/bitExpert/magento2-force-login/issues/142#issuecomment-540192305

Allow Magento admin to log in as customer

---

.github/workflows/ci.yml

Run CI against all supported Magento versions.

Extend CI pipeline with more Magento versions

---

etc/db_schema_whitelist.json

Add db_schema_whitelist.json to fix issue #220
